### ISSUE TITLE
Microsoft Graph API, Client error authenticating

### ISSUE THREAD

**Issue by saketrocx** [microsoftgraph/msgraph-training-android#37]
**I visited this below link to start sample android app for using graph api for microsoft teams.**

https://developer.microsoft.com/en-us/graph/quick-start?appID=1790d094-XXXX-XXXX-b55a-XXXXXXX39e7&appName=My%20Android%20App&redirectUrl=http://localhost:8000&platform=option-android

**But I am getting below error when i am trying to sign in.**

2020-09-22 16:49:34.322 31281-31281/com.example.graphtutorial E/AUTH: Client error authenticating
    com.microsoft.identity.client.exception.MsalClientException: 
        at com.microsoft.identity.client.SingleAccountPublicClientApplication.signIn(SingleAccountPublicClientApplication.java:188)
        at com.example.graphtutorial.AuthenticationHelper.acquireTokenInteractively(AuthenticationHelper.java:63)
        at com.example.graphtutorial.MainActivity.doInteractiveSignIn(MainActivity.java:243)
        at com.example.graphtutorial.MainActivity.access$500(MainActivity.java:33)
        at com.example.graphtutorial.MainActivity$2.onError(MainActivity.java:277)
        at com.microsoft.identity.client.SingleAccountPublicClientApplication$3.onError(SingleAccountPublicClientApplication.java:245)
        at com.microsoft.identity.client.SingleAccountPublicClientApplication$3.onError(SingleAccountPublicClientApplication.java:213)
        at com.microsoft.identity.common.internal.controllers.CommandDispatcher$2.run(CommandDispatcher.java:184)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7520)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by jasonjoh** [comment]
Unfortunately all that tells me is that you hit an internal error in the MSAL library. Can you set some breakpoints in `onError` in MainActivity.java and see if there is any additional information inside the exception, like error codes or messages?

**Comment by saketrocx** [comment]
@jasonjoh This exception i am getting when it is going for method acquireTokenInteractively() com.microsoft.identity.client.exception.MsalClientException: No cached accounts found for the supplied homeAccountId

**Comment by saketrocx** [comment]
@jasonjoh I fixed the problem, actually when i refactor package name, i forgot to change applicationID in gradle file.
It got fixed. Thanks
