### ISSUE TITLE
CoreHttpProvider[sendRequestInternal] - 424Error during http request

### ISSUE THREAD

**Issue by saketrocx** [microsoftgraph/msgraph-training-android#39]
**These are the scopes i am providing in authenticationHelper class in android.**

private String[] mScopes = { "User.Read", "Calendars.Read", "User.ReadWrite", "User.ReadWrite.All", "OnlineMeetings.Read", "OnlineMeetings.ReadWrite"};

**This what i am getting from token.**

 "scp": "AccessReview.Read.All AccessReview.ReadWrite.All Application.Read.All Application.ReadWrite.All Directory.AccessAsUser.All Directory.Read.All Directory.ReadWrite.All Files.Read Files.Read.All Mail.Read Mail.ReadBasic Mail.ReadWrite OnlineMeetings.Read OnlineMeetings.ReadWrite openid Organization.Read.All Organization.ReadWrite.All OrgContact.Read.All profile Tasks.ReadWrite User.Read User.Read.All User.ReadBasic.All User.ReadWrite User.ReadWrite.All email",

**In Azure AD , these are the api permissions i have added.**
<img width="1016" alt="Screen Shot 2020-09-29 at 1 12 49 PM" src="https://user-images.githubusercontent.com/71705094/94528079-86160d80-0255-11eb-9e1b-1785b24ae461.png">

**I am able to update users from graph explorer.**

<img width="801" alt="Screen Shot 2020-09-29 at 1 19 08 PM" src="https://user-images.githubusercontent.com/71705094/94528707-63d0bf80-0256-11eb-8a02-891372c1f7c9.png">

**But While using below code in android giving error.**

User user = new User();
        LinkedList<String> businessPhonesList = new LinkedList<String>();
        businessPhonesList.add("79XXXXXX94");
        user.businessPhones = businessPhonesList;
        user.officeLocation = "Bangalore";

        mClient.me()
                .buildRequest()
                .patch(user);

implementation 'com.microsoft.identity.client:msal:1.4.0'
implementation 'com.microsoft.graph:microsoft-graph:1.7.1'

**I am getting this error while calling above method.**

2020-09-29 13:14:13.361 16702-16702/com.XXX.XXXXX E/global: CoreHttpProvider[sendRequestInternal] - 424Error during http request
2020-09-29 13:14:13.361 16702-16702/com.XXX.XXXXX E/global: Throwable detail: com.microsoft.graph.core.ClientException: Error during http request
2020-09-29 13:14:13.362 16702-16702/com.XXX.XXXXX E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.XXX.XXXXX, PID: 16702
    com.microsoft.graph.core.ClientException: Error during http request
        at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:422)
        at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:204)
        at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:184)
        at com.microsoft.graph.http.BaseRequest.send(BaseRequest.java:306)
        at com.microsoft.graph.requests.extensions.UserRequest.patch(UserRequest.java:91)
        at com.phtl.teamsapp.GraphHelper.updateUser(GraphHelper.java:66)
        at com.phtl.teamsapp.CalendarFragment$1.onSuccess(CalendarFragment.java:48)

**Comment by jasonjoh** [comment]
I reproduce this in Graph Explorer as well. I don't believe users can update `officeLocation`. That information is considered to be "owned" by the company, not the user. At least that's how it was explained to me by the identity team :D.

See https://docs.microsoft.com/graph/permissions-reference?context=graph%2Fapi%2Fbeta&view=graph-rest-beta#remarks-29

> User.ReadWrite and User.Readwrite.All delegated permissions allow the app to update the following profile properties for work or school accounts:
> 
> - aboutMe
> - birthday
> - hireDate
> - interests
> - mobilePhone
> - mySite
> - pastProjects
> - photo
> - preferredName
> - responsibilities
> - schools
> - skills
