### ISSUE TITLE
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by MattDing31** [microsoftgraph/msgraph-training-android#40]
I followed all the instructions from https://docs.microsoft.com/en-us/graph/tutorials/android. The Authentication is passed, but when I try to get user data or calendar events, an exception occurs. I run the same codes on 2 android sdk versions, on 4.4, it failed, but on 6.0, I can get the data I want. the following is the exception messages.

com.microsoft.graph.core.ClientException: Error during http request
        at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:422)
        at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:204)
        at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:184)
        at com.microsoft.graph.http.BaseCollectionRequest.send(BaseCollectionRequest.java:89)
        at com.microsoft.graph.requests.extensions.EventCollectionRequest.get(EventCollectionRequest.java:52)
        at com.microsoft.graph.requests.extensions.EventCollectionRequest$1.run(EventCollectionRequest.java:43)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
     Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:409)
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:319)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:283)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:168)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.microsoft.graph.httpcore.TelemetryHandler.intercept(TelemetryHandler.java:35)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.microsoft.graph.httpcore.RedirectHandler.intercept(RedirectHandler.java:123)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.microsoft.graph.httpcore.RetryHandler.intercept(RetryHandler.java:140)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.microsoft.graph.httpcore.AuthenticationHandler.intercept(AuthenticationHandler.java:31)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at okhttp3.RealCall.execute(RealCall.java:92)
        at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:356)
        at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:204) 
        at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:184) 
        at com.microsoft.graph.http.BaseCollectionRequest.send(BaseCollectionRequest.java:89) 
        at com.microsoft.graph.requests.extensions.EventCollectionRequest.get(EventCollectionRequest.java:52) 
        at com.microsoft.graph.requests.extensions.EventCollectionRequest$1.run(EventCollectionRequest.java:43) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:841) 
     Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:282)
    	at com.android.org

What am I missing? Thanks in advance.

**Comment by jasonjoh** [comment]
This looks like a certificate trust issue, though I can't imagine why it wouldn't trust the certificate for https://graph.microsoft.com (or the authority that issued it). You mentioned this failing on Android SDK 4.4 - this was written for SDK 10 so I can't guarantee that it will work on 4.4. It may be that the CA for the Graph site's cert wasn't around when 4.4 was published (just speculating).

I see a bunch of results when searching for the error which involve code to trust specific certs or trust all certs (dangerous!). You'll have to decide which approach is appropriate for your scenario if you must support SDK 4.4.

I'm marking this out of scope as this tutorial isn't intended to support older SDK versions.
